# Generated by Django 4.2.13 on 2024-07-07 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('voucher', 'Voucher'), ('giftcard', 'Gift Card'), ('coupon', 'Coupon')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('redeem_code', models.CharField(max_length=50)),
                ('store', models.CharField(max_length=255)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('code_type', models.CharField(choices=[('barcode', 'EAN13 Barcode'), ('qrcode', 'QR Code')], max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='giftcard',
            name='voucher_ptr',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Expenditure',
        ),
        migrations.DeleteModel(
            name='GiftCard',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
