# Generated by Django 4.2.13 on 2024-07-14 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
