# Generated by Django 4.2.14 on 2024-07-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_item_file_item_file_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file_content_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='file_data',
        ),
        migrations.RemoveField(
            model_name='item',
            name='file_name',
        ),
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
