# Generated by Django 4.2.13 on 2024-07-07 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_store_alter_item_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='code_type',
        ),
    ]
