# Generated by Django 4.2.13 on 2024-07-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_item_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file',
        ),
        migrations.AddField(
            model_name='item',
            name='file_data',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
