# Generated by Django 4.2.14 on 2024-07-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_item_file_content_type_remove_item_file_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file',
        ),
        migrations.AddField(
            model_name='item',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
