# Generated by Django 4.2.14 on 2024-07-22 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_item_file_item_file_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='file_path',
        ),
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
