# Generated by Django 4.2.13 on 2024-07-07 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_item_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='store',
        ),
        migrations.AddField(
            model_name='item',
            name='issuer',
            field=models.CharField(default='Jochen Schweizer', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
