# Generated by Django 4.2.14 on 2024-07-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_item_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='value_type',
            field=models.CharField(choices=[('money', 'Money'), ('percentage', 'Percentage')], default='money', max_length=20),
        ),
    ]
