# Generated by Django 4.2.13 on 2024-07-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_item_store_item_issuer_delete_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
