# Generated by Django 5.0.7 on 2024-08-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_item_value_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='logo_slug',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
