# Generated by Django 5.0.7 on 2024-08-05 19:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_item_logo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='issue_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
