# Generated by Django 5.1.3 on 2024-11-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_appsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsettings',
            options={'verbose_name': 'API Settings', 'verbose_name_plural': 'API Settings'},
        ),
    ]
