# Generated by Django 5.1.3 on 2025-01-10 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_appsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code_type',
            field=models.CharField(default='qrcode', max_length=50),
        ),
    ]
