# Generated by Django 5.1.3 on 2025-02-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_item_code_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code_type',
            field=models.CharField(default='qrcode', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='issuer',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='logo_slug',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='pin',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='redeem_code',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('voucher', 'Voucher'), ('giftcard', 'Gift Card'), ('coupon', 'Coupon'), ('loyaltycard', 'Loyalty Card')], max_length=100),
        ),
    ]
