# Generated by Django 5.1.3 on 2025-02-17 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_item_code_type_alter_item_issuer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expiry_notification_send',
            field=models.BooleanField(default=False),
        ),
    ]
