# Generated by Django 5.1.3 on 2025-02-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_item_expiry_notification_send'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='expiry_notification_send',
            new_name='default_expiry_notification_sent',
        ),
        migrations.AddField(
            model_name='item',
            name='final_expiry_notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
