# Generated by Django 5.2 on 2025-06-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_expiry_notification_send_item_default_expiry_notification_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='value_type',
            field=models.CharField(choices=[('money', 'Money'), ('percentage', 'Percentage'), ('multiplier', 'Multiplier')], default='money', max_length=20),
        ),
    ]
