# Generated by Django 5.2 on 2025-06-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_userpreference_show_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='show_description',
            field=models.BooleanField(default=False),
        ),
    ]
