# Generated by Django 5.2 on 2025-06-23 11:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_userpreference_show_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tile_color',
            field=models.CharField(blank=True, help_text='Hex code like #FF5733', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
    ]
