# Generated by Django 5.2 on 2026-01-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_item_tile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='sort_by',
            field=models.CharField(choices=[('expiry_date', 'Expiry Date'), ('name', 'Name'), ('issue_date', 'Creation Date'), ('value', 'Value')], default='expiry_date', max_length=20),
        ),
    ]
