# Generated by Django 5.2 on 2026-01-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_userpreference_sort_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='sort_order',
            field=models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], default='asc', max_length=4),
        ),
    ]
