# Generated by Django 5.2.11 on 2026-02-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_userpreference_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='view_mode',
            field=models.CharField(choices=[('detailed', 'Detailed'), ('compact', 'Compact')], default='detailed', max_length=10),
        ),
    ]
