# Generated by Django 5.2.11 on 2026-02-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_userpreference_view_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='view_mode',
        ),
    ]
