# Generated by Django 5.2.11 on 2026-04-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_userpreference_view_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='view_mode',
            field=models.CharField(choices=[('compact', 'Compact'), ('standard', 'Standard')], default='compact', max_length=10),
        ),
    ]
