# Generated by Django 5.2.11 on 2026-04-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_add_view_mode_and_is_pinned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='show_description',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='show_issue_date',
            field=models.BooleanField(default=False),
        ),
    ]
