# Generated by Django 5.2.13 on 2026-06-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_userpreference_show_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('AED', 'AED - UAE Dirham'), ('AUD', 'AUD - Australian Dollar'), ('BGN', 'BGN - Bulgarian Lev'), ('BRL', 'BRL - Brazilian Real'), ('CAD', 'CAD - Canadian Dollar'), ('CHF', 'CHF - Swiss Franc'), ('CNY', 'CNY - Chinese Yuan'), ('CZK', 'CZK - Czech Koruna'), ('DKK', 'DKK - Danish Krone'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('HKD', 'HKD - Hong Kong Dollar'), ('HRK', 'HRK - Croatian Kuna'), ('HUF', 'HUF - Hungarian Forint'), ('IDR', 'IDR - Indonesian Rupiah'), ('ILS', 'ILS - Israeli Shekel'), ('INR', 'INR - Indian Rupee'), ('JPY', 'JPY - Japanese Yen'), ('KRW', 'KRW - South Korean Won'), ('MXN', 'MXN - Mexican Peso'), ('MYR', 'MYR - Malaysian Ringgit'), ('NOK', 'NOK - Norwegian Krone'), ('NZD', 'NZD - New Zealand Dollar'), ('PHP', 'PHP - Philippine Peso'), ('PLN', 'PLN - Polish Zloty'), ('RON', 'RON - Romanian Leu'), ('RUB', 'RUB - Russian Ruble'), ('SEK', 'SEK - Swedish Krona'), ('SGD', 'SGD - Singapore Dollar'), ('THB', 'THB - Thai Baht'), ('TRY', 'TRY - Turkish Lira'), ('USD', 'USD - US Dollar'), ('ZAR', 'ZAR - South African Rand')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='default_currency',
            field=models.CharField(choices=[('AED', 'AED - UAE Dirham'), ('AUD', 'AUD - Australian Dollar'), ('BGN', 'BGN - Bulgarian Lev'), ('BRL', 'BRL - Brazilian Real'), ('CAD', 'CAD - Canadian Dollar'), ('CHF', 'CHF - Swiss Franc'), ('CNY', 'CNY - Chinese Yuan'), ('CZK', 'CZK - Czech Koruna'), ('DKK', 'DKK - Danish Krone'), ('EUR', 'EUR - Euro'), ('GBP', 'GBP - British Pound'), ('HKD', 'HKD - Hong Kong Dollar'), ('HRK', 'HRK - Croatian Kuna'), ('HUF', 'HUF - Hungarian Forint'), ('IDR', 'IDR - Indonesian Rupiah'), ('ILS', 'ILS - Israeli Shekel'), ('INR', 'INR - Indian Rupee'), ('JPY', 'JPY - Japanese Yen'), ('KRW', 'KRW - South Korean Won'), ('MXN', 'MXN - Mexican Peso'), ('MYR', 'MYR - Malaysian Ringgit'), ('NOK', 'NOK - Norwegian Krone'), ('NZD', 'NZD - New Zealand Dollar'), ('PHP', 'PHP - Philippine Peso'), ('PLN', 'PLN - Polish Zloty'), ('RON', 'RON - Romanian Leu'), ('RUB', 'RUB - Russian Ruble'), ('SEK', 'SEK - Swedish Krona'), ('SGD', 'SGD - Singapore Dollar'), ('THB', 'THB - Thai Baht'), ('TRY', 'TRY - Turkish Lira'), ('USD', 'USD - US Dollar'), ('ZAR', 'ZAR - South African Rand')], default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='fixer_api_key',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
